---
title: "R Notebook"
output: html_notebook
---
```{r}
library(janitor)
library(tidyverse)
library(ggplot2)
library(reshape2)
library(leaflet)
```

I am going to look at the deprivation data and look at the count of each deprivation 
```{r}
deprivation_data <- read_csv("raw_data/treatment_and_deprevation.csv") 
deprivation_data <- deprivation_data %>% clean_names()
head(deprivation_data) #I need to change the simd column to numeric otherwise it will be contiunious and we dont want that for the graph
tail(deprivation_data)
deprivation_data <- deprivation_data %>%
  filter(!is.na(simd)) #removing nas from here as we will be working with this variable often 

hospital_location <- read_csv("raw_data/current-hospital_flagged_location.csv")
hospital_location <- hospital_location %>% clean_names()

# I am going to join the data to check out the locations

deprivation_data_join <- left_join(hospital_location, deprivation_data, "location")


#changing simd to integer
deprivation_data <- deprivation_data %>%
  mutate(simd = as.factor(simd))

#making a set which looks at quarter and simd and groups them
simd_quarter <- deprivation_data %>%
  group_by(quarter) %>%
  count(simd)

ggplot(simd_quarter) +
  aes(x = quarter, y = n, fill = simd) +
  geom_col()

```


```{r}
#looking at the total count of each simd
simd_count <- deprivation_data %>%
 group_by(simd) %>%
  summarise(count = n())
```

```{r}
#looking at location, total count of simd and admission type
simd_location <- deprivation_data_join %>%
  group_by(location_name, simd, admission_type) %>%
    summarise(count = n())


simd_count <- deprivation_data %>%
 group_by(quarter, simd, admission_type) %>%
  summarise(count = n())

#counting the sum amount of admission types in each quarter and simd category 
simd_count %>%
ggplot() +
  geom_line(aes(x = quarter, y = count, group = admission_type, colour = simd))

#looking atadmission types and simd total
simd_admission <- deprivation_data %>%
  group_by(admission_type, simd) %>%
  summarise(count = n())

simd_admission %>%
ggplot() +
  aes(x = admission_type, y = count, fill = simd , position = "dodge") +
  geom_col() +
  facet_grid(~ simd) +
  theme(axis.text.x = element_text(angle = 90), legend.position = "none") +
  labs(
    x = "Admission type",
    y = "individuals"
  )
```
```{r}
#plotting each simd level and the total count in each qurter into a facet wrap
simd_quarter %>%
ggplot() +
  aes(x = quarter, y = n, fill = simd) +
  geom_line(group = 1) +
  facet_wrap(~ simd) +
  theme(axis.text.x = element_text(angle = 90))
```

```{r}


cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#D55E00", "#0072B2", "#D55E00", "#CC79A7")

simd_quarter %>%
  ggplot(aes(x = quarter, y = n, colour = as.factor(simd), group = simd)) +
  geom_line() +
  scale_color_manual(values = cbbPalette) +
  theme_light() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(
    x = "\nQuarter and Year",
    y = "Count of individuals in each SIMD\n",
    colour = "SIMD",
    title = "The count of individuals in each SIMD across 2016 Q2 -2021 Q2",
    subtitle = "Deprivation levels: 1(Most Deprived) - 5(Least Deprived)\n"
  )
```
A plot to check the count of individuals in different admission types and if it correlates to the SIMD
```{r}

simd_admission %>%
  ggplot() +
  aes(x = admission_type, y = count, fill = simd, group = simd) +
  geom_col() +
  theme_light() +
  theme(axis.text.x = element_text(angle = 90)) 
#the graph shows not that much difference between simd and what admissions type they have come in for. All seem to be pretty equal. 
```

```{r}
simd_location %>%
  ggplot(aes(x = location_name, y = count, fill = as.factor(simd), group = simd)) +
  geom_col() +
  scale_color_manual(values = cbbPalette) +
  theme_light() +
  theme(axis.text.x = element_text(angle = 90))
```

```{r}
ane <- read_csv("raw_data/monthly_a&e_activity_and_waiting_times.csv")
```

